name: Laravel CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3' # Версія, яка стабільно підтримує твій стек
          extensions: mbstring, xml, sqlite3, pdo_sqlite

      - name: Install Dependencies
        run: composer install --prefer-dist --no-ansi --no-interaction --no-progress

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Generate key
        run: php artisan key:generate

      # Перевірка стилю коду (Linter)
      - name: Run Pint (Style Check)
        run: ./vendor/bin/pint --test

      # Запуск тестів
      - name: Execute tests
        run: php artisan test
